-- Seed / backup data captured from a running installation.
-- Generated by scripts/generate_seed_migrations.py -- do not edit by hand.
--
-- Idempotent: every row uses "INSERT ... ON CONFLICT DO NOTHING" and identity
-- sequences are realigned afterwards, so applying this on an existing database is safe.


-- auth_users
INSERT INTO public.auth_users (id, email, name, role) VALUES (1, 'admin@example.com', 'Admin', 'ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO public.auth_users (id, email, name, role) VALUES (6, 'mehedi@gmail.com', 'mehedi', 'USER') ON CONFLICT DO NOTHING;
INSERT INTO public.auth_users (id, email, name, role) VALUES (8, 'habibulbashar102001@gmail.com', 'Habibul Basar', 'ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO public.auth_users (id, email, name, role) VALUES (12, 'khansaifullahali3@gmail.com', 'saifullah ali khan', 'MAINTAINER') ON CONFLICT DO NOTHING;
INSERT INTO public.auth_users (id, email, name, role) VALUES (9, 'aptms02@gmail.com', 'APTMS', 'SALESMAN') ON CONFLICT DO NOTHING;
INSERT INTO public.auth_users (id, email, name, role) VALUES (11, 'solemonshah5@gmail.com', 'solemon shah', 'MANAGER') ON CONFLICT DO NOTHING;
INSERT INTO public.auth_users (id, email, name, role) VALUES (10, 'habibulbashar.cse@gmail.com', 'Habibul Bashar', 'USER') ON CONFLICT DO NOTHING;
SELECT pg_catalog.setval('public.auth_users_id_seq', 12, true);
