CREATE TABLE orders (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    product_id      BIGINT NOT NULL,
    quantity        INTEGER NOT NULL,
    status          VARCHAR(255) NOT NULL DEFAULT 'PENDING',
    product_updated BOOLEAN NOT NULL DEFAULT false
);
