CREATE TABLE cart_items (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT NOT NULL,
    product_id         BIGINT NOT NULL,
    name               VARCHAR(255),
    price              NUMERIC(38, 2),
    quantity           INTEGER NOT NULL,
    available_quantity INTEGER,
    CONSTRAINT uk_cart_user_product UNIQUE (user_id, product_id)
);
