-- Seed / backup data captured from a running installation.
-- Generated by scripts/generate_seed_migrations.py -- do not edit by hand.
--
-- Idempotent: every row uses "INSERT ... ON CONFLICT DO NOTHING" and identity
-- sequences are realigned afterwards, so applying this on an existing database is safe.


-- orders
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (32, 12, 4, 17, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (33, 12, 2, 17, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (34, 9, 1, 17, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (35, 12, 1, 17, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (36, 15, 2, 17, 'CANCELLED', false) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (37, 12, 1, 17, 'CANCELLED', false) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (38, 15, 1, 17, 'CANCELLED', false) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (85, 14, 1, 20, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (62, 1, 1, 17, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (39, 1, 2, 1, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (40, 14, 2, 1, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (41, 14, 3, 1, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (42, 15, 1, 17, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (43, 15, 1, 17, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (45, 5, 1, 1, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (44, 14, 1, 17, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (46, 14, 1, 17, 'CANCELLED', false) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (48, 12, 1, 17, 'CANCELLED', false) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (87, 13, 1, 20, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (47, 5, 2, 1, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (49, 14, 1, 17, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (50, 14, 2, 17, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (51, 12, 1, 17, 'CANCELLED', false) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (52, 1, 1, 17, 'CANCELLED', false) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (53, 1, 1, 17, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (88, 12, 1, 17, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (54, 5, 1, 17, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (66, 13, 1, 19, 'CANCELLED', false) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (31, 14, 1, 17, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (65, 12, 1, 19, 'CANCELLED', false) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (67, 12, 1, 19, 'CANCELLED', false) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (58, 11, 1, 17, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (89, 13, 1, 17, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (59, 15, 1, 17, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (64, 1, 1, 17, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (63, 14, 1, 17, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (57, 1, 1, 17, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (68, 14, 1, 19, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (56, 5, 1, 17, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (69, 12, 1, 19, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (55, 2, 1, 17, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (60, 1, 1, 17, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (90, 13, 1, 17, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (61, 14, 1, 17, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (70, 14, 1, 19, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (71, 14, 1, 19, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (91, 13, 1, 17, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (72, 14, 1, 19, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (92, 2, 1, 17, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (74, 13, 1, 19, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (73, 15, 1, 19, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (75, 13, 1, 19, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (93, 15, 1, 22, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (76, 13, 1, 20, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (77, 15, 50, 17, 'CONFIRMING', false) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (79, 13, 1, 20, 'CANCELLED', false) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (78, 14, 1, 20, 'CANCELLED', false) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (80, 15, 1, 20, 'CANCELLED', false) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (81, 15, 1, 20, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (82, 15, 1, 20, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (83, 13, 1, 20, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (86, 11, 1, 20, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (84, 13, 1, 20, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (94, 3, 1, 18, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (95, 1, 1, 20, 'CANCELLED', false) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (96, 2, 1, 20, 'CANCELLED', false) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (97, 3, 1, 20, 'CANCELLED', false) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (98, 4, 1, 20, 'CANCELLED', false) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (99, 5, 1, 20, 'CANCELLED', false) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (100, 6, 1, 20, 'CANCELLED', false) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (101, 7, 1, 20, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (107, 35, 2, 24, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (102, 8, 1, 20, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (103, 9, 1, 20, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (104, 43, 1, 20, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (105, 40, 1, 20, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (106, 42, 2, 20, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (108, 23, 1, 24, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (109, 11, 5, 20, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (110, 12, 13, 20, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (111, 42, 1, 20, 'CANCELLED', false) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (112, 42, 1, 20, 'CONFIRMED', true) ON CONFLICT DO NOTHING;
INSERT INTO public.orders (id, product_id, quantity, user_id, status, product_updated) VALUES (113, 43, 1, 20, 'PENDING', false) ON CONFLICT DO NOTHING;
SELECT pg_catalog.setval('public.orders_id_seq', 113, true);

-- cart_items
INSERT INTO public.cart_items (id, user_id, product_id, name, price, quantity, available_quantity) VALUES (6, 20, 43, 'shaban', 70.00, 1, 49) ON CONFLICT DO NOTHING;
INSERT INTO public.cart_items (id, user_id, product_id, name, price, quantity, available_quantity) VALUES (7, 20, 42, 'Lux Soap', 80.00, 1, 7) ON CONFLICT DO NOTHING;
SELECT pg_catalog.setval('public.cart_items_id_seq', 7, true);
