server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  application:
    name: user-service

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true
        register-health-check: false
    loadbalancer:
      enabled: true

  cache:
    type: jcache
    jcache:
      config: classpath:ehcache.xml

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration

  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    username: lemon
    password: lemon

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    deserialization:
      fail-on-null-for-primitives: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
          issuer-uri: https://accounts.google.com

jwt:
  secret: 7a4f0c9b2e5d8a1c3f6b9e2d4a7c0f3b6e9a2d4c7f0b3e6a9d2c4f7b0e3a6c
  issuer: auth-service

auth-service:
  base-url: http://auth-service

oauth2:
  google-client-id: 431304946036-ra24hsuvu0gviu7bsd77ivvhsio0qhpu.apps.googleusercontent.com
  admin-emails:
    - admin@example.com
    - habibulbashar102001@gmail.com

