server:
  port: 8081

spring:
  application:
    name: user-service

  cache:
    type: jcache
    jcache:
      config: classpath:ehcache.xml

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    username: lemon
    password: lemon

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    deserialization:
      fail-on-null-for-primitives: false

