CREATE TABLE message_logs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name VARCHAR(255) NOT NULL,
    direction    VARCHAR(255) NOT NULL,
    routing_key  VARCHAR(255) NOT NULL,
    queue        VARCHAR(255),
    email        VARCHAR(255),
    payload      TEXT,
    status       VARCHAR(255) NOT NULL,
    detail       TEXT,
    created_at   TIMESTAMP(6) NOT NULL
);
