-- Seed / backup data captured from a running installation.
-- Generated by scripts/generate_seed_migrations.py -- do not edit by hand.
--
-- Idempotent: every row uses "INSERT ... ON CONFLICT DO NOTHING" and identity
-- sequences are realigned afterwards, so applying this on an existing database is safe.


-- users
INSERT INTO public.users (id, email, name, active, role) VALUES (18, 'habibulbashar102001@gmail.com', 'Habibul Basar', true, 'ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO public.users (id, email, name, active, role) VALUES (22, 'khansaifullahali3@gmail.com', 'saifullah ali khan', true, 'MAINTAINER') ON CONFLICT DO NOTHING;
INSERT INTO public.users (id, email, name, active, role) VALUES (19, 'aptms02@gmail.com', 'APTMS', true, 'SALESMAN') ON CONFLICT DO NOTHING;
INSERT INTO public.users (id, email, name, active, role) VALUES (21, 'solemonshah5@gmail.com', 'solemon shah', true, 'MANAGER') ON CONFLICT DO NOTHING;
INSERT INTO public.users (id, email, name, active, role) VALUES (17, 'mehedi@gmail.com', 'mehedi', false, 'USER') ON CONFLICT DO NOTHING;
INSERT INTO public.users (id, email, name, active, role) VALUES (24, 'codex.test2@example.com', 'Codex T2', false, 'MAINTAINER') ON CONFLICT DO NOTHING;
INSERT INTO public.users (id, email, name, active, role) VALUES (20, 'habibulbashar.cse@gmail.com', 'Habibul Bashar', true, 'USER') ON CONFLICT DO NOTHING;
INSERT INTO public.users (id, email, name, active, role) VALUES (25, 'probe@example.com', 'Probe', true, 'USER') ON CONFLICT DO NOTHING;
SELECT pg_catalog.setval('public.users_id_seq', 25, true);
