package com.example.productservice.entity;

public enum ProductStatus {
    PENDING_MANAGER,
    PENDING_PRODUCT_SPECIALIST,
    PENDING_SALESMAN,
    PENDING_ADMIN,
    APPROVED,
    REJECTED_BY_MANAGER,
    REJECTED_BY_PRODUCT_SPECIALIST,
    REJECTED_BY_SALESMAN,
    REJECTED_BY_ADMIN
}
