server:
  port: 8082
spring:
  application:
    name: product-service

  cache:
    type: jcache
    jcache:
      config: classpath:ehcache.xml

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
        spring.json.trusted.packages: com.example.event

  datasource:
    url: jdbc:postgresql://localhost:5432/product-service
    username: lemon
    password: lemon
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

log-service:
  base-url: http://localhost:8084

jwt:
  secret: microservice-tests-super-secret-key-please-change-0123456789