ALTER TABLE products ADD COLUMN status VARCHAR(255) NOT NULL DEFAULT 'APPROVED';
ALTER TABLE products ADD COLUMN rejection_reason TEXT;
ALTER TABLE products ADD COLUMN rejected_by_role VARCHAR(255);
ALTER TABLE products ADD COLUMN created_by VARCHAR(255);
ALTER TABLE products ADD COLUMN maintainer_reviewer VARCHAR(255);
ALTER TABLE products ADD COLUMN admin_reviewer VARCHAR(255);

CREATE TABLE product_notifications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      BIGINT NOT NULL,
    product_name    VARCHAR(255),
    recipient_email VARCHAR(255),
    recipient_role  VARCHAR(255),
    message         TEXT NOT NULL,
    created_at      TIMESTAMP(6) NOT NULL,
    read_flag       BOOLEAN NOT NULL DEFAULT false
);
