#!/usr/bin/env python3
"""Generate Flyway seed migrations from a running PostgreSQL database.

It dumps each service's data with ``pg_dump --column-inserts --on-conflict-do-nothing``
and writes a versioned migration into the service's ``db/migration`` folder, so a fresh
clone gets the same schema *and* data automatically.

The dump is executed inside the Postgres container (override with --container) because
``pg_dump`` may only be available there.

Usage:
    python3 scripts/generate_seed_migrations.py [--container NAME]
"""
from __future__ import annotations

import argparse
import subprocess

# database -> (migration file, [tables])
TARGETS = {
    "auth-service": ("auth-service/src/main/resources/db/migration/V2__seed_data.sql", ["auth_users"]),
    "user-service": ("user-service/src/main/resources/db/migration/V2__seed_data.sql", ["users"]),
    "product-service": (
        "product-service/src/main/resources/db/migration/V6__seed_data.sql",
        ["products", "product_notifications", "stock_updates"],
    ),
    "order-service": (
        "order-service/src/main/resources/db/migration/V3__seed_data.sql",
        ["orders", "cart_items"],
    ),
    "log-db": ("log-service/src/main/resources/db/migration/V2__seed_data.sql", ["message_logs"]),
}

HEADER = """-- Seed / backup data captured from a running installation.
-- Generated by scripts/generate_seed_migrations.py -- do not edit by hand.
--
-- Idempotent: every row uses "INSERT ... ON CONFLICT DO NOTHING" and identity
-- sequences are realigned afterwards, so applying this on an existing database is safe.
"""


def dump(container: str, db: str, table: str) -> list[str]:
    cmd = [
        "docker", "exec", container,
        "pg_dump", "-U", "lemon", "-d", db,
        "--data-only", "--column-inserts", "--on-conflict-do-nothing",
        "--no-owner", "--no-privileges", "--table", table,
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, check=True)
    keep = []
    for line in result.stdout.splitlines():
        stripped = line.strip()
        if stripped.startswith("INSERT INTO ") or stripped.startswith("SELECT pg_catalog.setval("):
            keep.append(line)
    return keep


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--container", default="bigtheta-db-postgresql-latest-container")
    args = parser.parse_args()

    for db, (path, tables) in TARGETS.items():
        sections = [HEADER.format(service=db)]
        total = 0
        for table in tables:
            lines = dump(args.container, db, table)
            total += len(lines)
            sections.append(f"\n-- {table}")
            sections.append("\n".join(lines))
        with open(path, "w", encoding="utf-8") as handle:
            handle.write("\n".join(sections).rstrip() + "\n")
        print(f"wrote {path} ({total} statements)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
